### ISSUE TITLE
No/partial transform to ES5

### ISSUE THREAD

**Issue by adi-works** [Justineo/vue-void#1]
Getting an error with Uglify.

**Comment by Justineo** [comment]
It's intentional. The piece of code is rather trivial, you can just copy-paste into your own project I think. This project is more like a POC and a place to call for native support in Vue core.

https://github.com/Justineo/vue-void/blob/a2deeab710bd723f7311afb8b1504f2b21746319/src/components/VVoid.js#L1-L6

**Comment by adi-works** [comment]
Yes, it should be part of Vue core. Thanks.
